dataset:
  path: /project/hippocampus/common/kaveh/dataset/HCP_OASIS_7.4.1
  split_file: /project/hippocampus/common/kaveh/dataset/dataset_split.csv
  split_name: test    

evaluation:
  num_classes: 9
  exclude_background: true
  nsd_tolerance_vox: 1.0

outputs:
  root: /project/hippocampus/common/kaveh/workspace/NipoSimCortex/ckt/segmentation
  pred_save_dir: ${outputs.root}/exp1_aug_500_ddp/predictions_HCP_OASIS
  log_dir:  ${outputs.root}/exp1_aug_500_ddp/evaluations_HCP_OASIS
  eval_csv: ${outputs.root}/exp1_aug_500_ddp/evaluations_HCP_OASIS/seg_eval_test.csv

hydra:
  run:
    dir: ${outputs.log_dir}
  output_subdir: null
