dataset:
  path: /home/at83760/workspace/dataset/CNP_LA5C_BIDS_KM/preprocessed_mni
  split_file: /home/at83760/workspace/dataset/CNP_LA5C_BIDS_KM/subjects_data.csv
  pad_mult: 16
  split_name: test       

trainer:
  device: cuda:0
  batch_size: 2        
  num_workers: 4

model:
  in_channels: 1
  out_channels: 9
  ckpt_path: /home/at83760/workspace/fall2025/SimCortexPP/ckpts/segmentation/exp1_500_ddp/checkpoints/seg_best_dice.pt

outputs:
  root: /home/at83760/workspace/fall2025/SimCortexPP/ckpts/segmentation
  log_dir:  ${outputs.root}/exp1_500_ddp/logs_predict_CNP
  pred_save_dir: ${outputs.root}/exp1_500_ddp/predictions_CNP

hydra:
  run:
    dir: ${outputs.log_dir}
  output_subdir: null
