dataset:
  path: /project/hippocampus/common/kaveh/dataset/HCP_OASIS_7.4.1
  split_file: /project/hippocampus/common/kaveh/dataset/dataset_split.csv
  pad_mult: 16
  split_name: test       

trainer:
  device: cuda:0
  batch_size: 2        
  num_workers: 4

model:
  in_channels: 1
  out_channels: 9
  ckpt_path: /project/hippocampus/common/kaveh/workspace/NipoSimCortex/ckt/segmentation/exp1_aug_500_ddp/checkpoints/seg_best_dice.pt


outputs:
  root: /project/hippocampus/common/kaveh/workspace/NipoSimCortex/ckt/segmentation
  log_dir:  ${outputs.root}/exp1_aug_500_ddp/logs_predict_HCP_OASIS
  pred_save_dir: ${outputs.root}/exp1_aug_500_ddp/predictions_HCP_OASIS

hydra:
  run:
    dir: ${outputs.log_dir}
  output_subdir: null
