dataset:
  path: /home/at83760/workspace/dataset/HCP_OASIS_7.4.1
  split_file: /home/at83760/workspace/dataset/dataset_split.csv
  pad_mult: 16         
  train_split: train
  val_split: val
  augment: true

trainer:
  device: cuda:0
  num_epochs: 500
  learning_rate: 1e-4
  batch_size: 6
  num_workers: 4
  validation_interval: 15  
  save_interval: 20     
  dice_weight: 1.0        
  use_ddp: true
  data_parallel: false

model:
  in_channels: 1
  out_channels: 9

outputs:
  root: /home/at83760/workspace/fall2025/SimCortexPP/ckpts/segmentation   
  log_dir:  ${outputs.root}/logs
  ckpt_dir: ${outputs.root}/checkpoints

hydra:
  run:
    dir: ${outputs.log_dir}  
  output_subdir: null
